[package]
name = "rust_learning_practices_tests"
version = "0.1.0"
authors = ["Riton <ritonelion@outlook.com>"]
edition = "2018"

[dependencies]
rand = "0.6"
num = "0.2"
libc = "0.2"

[build-dependencies]
cc = "1.0"

